---
- name: Install ACL
  become: true
  apt: name=acl

- name: Configure ACL on each path
  include_tasks: acl-item.yml
  with_items: "{{ server_writable_paths }}"
  loop_control:
    loop_var: acl_item
