---
- name: Update apt cache
  become: true
  apt: update_cache=yes cache_valid_time=86400

- include_tasks: "php.yml"
  when: server_php_support

- include_tasks: "acl.yml"

- name: Install basic packages
  become: true
  apt: name={{item}}
  with_items: "{{ server_packages }}"
  when: server_packages|length > 0

- name: Set up iptables rules
  become: true
  template:
    src: "{{ server_iptables_rules_template }}"
    dest: "{{ server_iptables_rules_path }}"
    owner: root
    group: root
    mode: "0644"
  notify: restart iptables

- name: Set up pre-up script for restoring iptables rules on reboot
  become: true
  template:
    src: "{{ server_iptables_preup_template }}"
    dest: "{{ server_iptables_preup_path }}"
    owner: root
    group: root
    mode: "0744"
