---
- name: Update apt cache
  become: true
  apt: update_cache=yes cache_valid_time=86400

- name: Add dependencies for PHP versions (Debian).
  become: true
  apt:
    name: "{{ item }}"
  with_items: "{{ server_php_dependencies }}"

- name: Add Ondrej Sury's apt key (Debian).
  become: true
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: Add Ondrej Sury's repo (Debian).
  become: true
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present
  register: php_ondrej_debian_repo

- name: Update apt cache
  become: true
  apt: update_cache=yes cache_valid_time=86400

- name: Install tools
  become: true
  apt: name={{item}}
  with_items: "{{ server_tools }}"

- name: Set up iptables rules
  become: true
  copy: src=iptables dest=/etc/iptables.rules
  notify: restart iptables

- name: Ensure writable paths exists
  become: true
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ server_writable_paths }}"

- name: Set up files permissions
  become: true
  acl:
    path: "{{ item }}"
    permissions: rwX
    entity: "{{ ansible_user }}"
    etype: user
    recursive: yes
    follow: yes
    default: no
    state: present
  with_items: "{{ server_writable_paths }}"

- name: Set up default files permissions
  become: true
  acl:
    path: "{{ item }}"
    permissions: rwX
    entity: "{{ ansible_user }}"
    etype: user
    recursive: yes
    follow: yes
    default: yes
    state: present
  with_items: "{{ server_writable_paths }}"
